name: Test release-deb.sh
on: 
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:

  build:
    name: Build
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        platform: [ x86_64, aarch64]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y qemu-user-static binfmt-support
          scripts/release-deb.sh 999 --platform ${{ matrix.platform }}
